language: node_js
node_js:
- '8'
deploy:
  provider: cloudfoundry
  api: https://api.eu-gb.bluemix.net
  username: $BLUEMIX_USERNAME
  password: $BLUEMIX_PASSWORD
  organization: $BLUEMIX_ORGANIZATION
  space: $BLUEMIX_SPACE
  on:
    repo: hunttis/scrappy
    branch: master
